version: "3"
volumes:
    Database3:
services:
    post:
        image: postgres
        environment: 
            - "POSTGRES_USER=gutendex"
            - "POSTGRES_PASSWORD=pass"
            - "POSTGRES_DB=gutendex"
        ports:
            - "81:5432"
        volumes:
            - "Database3:/var/lib/postgresql/data"
            # - "/home/bynet13/Desktop/projectGutenberg/init-conf.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    guten:
        build: .
        ports:
            - "80:8000"
        volumes:
            - "/home/bynet13/Desktop/projectGutenberg/gutendex/.env.template:/app/gutendex/.env"
        environment: 
            - "SECRET_KEY=kappa123"
    nginx:
        image: nginx
        ports:
            - "82:80"
        volumes:
            - "/home/bynet13/Desktop/projectGutenberg/nginx.conf:/etc/nginx/nginx.conf"
            - "/home/bynet13/Desktop/projectGutenberg/static:/usr/share/nginx/html/static"
        depends_on: 
            - "guten"